### ISSUE TITLE
bug: Replacement   bool   `json:"replacement,omitempty"`

### ISSUE THREAD

**Issue by IndieRobert** [AkshatM/caprice#6]
Setting replacement to false doesn't work because of the omitempty. Replacement is omitted in the request and get back as true in the response.

**Comment by AkshatM** [comment]
This is a very good catch, thank you. Let me add test cases and a fix.

**Comment by AkshatM** [comment]
PR #7 has fixed this, and has been merged. Please either update your local copy or continue to use `github.com/AkshatM/caprice` in the meantime.

I'm working on adding testcases in a follow-up PR to ensure this doesn't happen again. This will be work performed under https://github.com/AkshatM/caprice/issues/5
